import React from 'react';
import { Scale, AlertTriangle } from 'lucide-react';
import SEO from '../components/SEO';

const Terms: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto py-12 animate-in slide-in-from-bottom-4 duration-500">
      <SEO 
        title="Terms of Service"
        description="Read the Terms of Service for MyHumanStats. Includes medical disclaimers and usage guidelines."
      />
      
      <div className="mb-12 border-b border-zinc-800 pb-8">
        <div className="flex items-center gap-3 mb-4">
           <Scale className="text-primary-500" size={24} />
           <span className="text-primary-500 font-mono text-xs uppercase tracking-widest">Legal Document</span>
        </div>
        <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-zinc-500 text-sm font-mono">Last Updated: January 20, 2026</p>
      </div>

      {/* Critical Disclaimer */}
      <div className="bg-red-900/10 border border-red-900/50 p-6 rounded-lg mb-10 flex gap-4">
         <AlertTriangle className="text-red-500 shrink-0 mt-1" size={24} />
         <div className="text-sm text-red-200 leading-relaxed">
            <h3 className="font-bold text-red-400 mb-2 uppercase tracking-wider text-xs">Medical Disclaimer</h3>
            <p>
               The content, tests, and results on MyHumanStats.org are for <strong>informational and entertainment purposes only</strong>. They do NOT constitute medical advice, diagnosis, or treatment. Never disregard professional medical advice or delay in seeking it because of something you have read on this website. If you suspect you have a medical condition (e.g., hearing loss, color blindness, ADHD), please consult a qualified healthcare provider.
            </p>
         </div>
      </div>

      <div className="space-y-10 text-zinc-300 leading-relaxed font-sans text-sm md:text-base">
        
        <section>
          <h2 className="text-xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the website located at <strong>https://myhumanstats.org</strong> (the "Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-4">2. Use License</h2>
          <p>
            Permission is granted to temporarily access the materials (tests and information) on MyHumanStats for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license, you may not:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-zinc-400">
            <li>Modify or copy the materials;</li>
            <li>Use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
            <li>Attempt to decompile or reverse engineer any software contained on the MyHumanStats website;</li>
            <li>Remove any copyright or other proprietary notations from the materials.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-4">3. Accuracy of Results</h2>
          <p>
            While we strive for accuracy, the tests provided on MyHumanStats are subject to limitations of your device hardware (e.g., screen color calibration, speaker quality, microphone fidelity) and browser performance. We do not warrant that the results generated by these tests are accurate, complete, or reliable for any scientific or medical purpose.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-4">4. Limitations</h2>
          <p>
            In no event shall MyHumanStats or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on MyHumanStats, even if MyHumanStats has been notified orally or in writing of the possibility of such damage.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-4">5. Links</h2>
          <p>
            MyHumanStats has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by MyHumanStats. Use of any such linked website is at the user's own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-4">6. Governing Law</h2>
          <p>
            These terms and conditions are governed by and construed in accordance with the laws of the United States and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-4">7. Contact</h2>
          <p>
            For legal inquiries regarding these Terms of Service, please contact: <a href="mailto:info@myhumanstats.org" className="text-primary-400 hover:underline">info@myhumanstats.org</a>.
          </p>
        </section>

      </div>
    </div>
  );
};

export default Terms;